Resources:
    SNSandDynamoDBRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.stage}-SNSandDynamoDBRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: SNSandDynamoDBPermissionPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: 
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - sns:Publish 
                    - sns:SetSMSAttributes
                    - sns:ListPhoneNumbersOptedOut
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - dynamodb:DescribeTable
                    - dynamodb:Query
                    - dynamodb:Scan
                  Resource: 
                    - "Fn::GetAtt": [ TargetPhoneTable, Arn ]
